name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        echo "PSPDEV_TAG=ghcr.io/pspdev/pspdev:v20260201" >> $GITHUB_ENV

    - name: Build
      run: |
        docker run --rm -i -v ./:/work_dir -w /work_dir "$PSPDEV_TAG" make
        mkdir -p PSP/GAME/mhp3_patcher
        mv EBOOT.PBP PSP/GAME/mhp3_patcher/
        mv PARAM.SFO PSP/GAME/mhp3_patcher/

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: mhp3_patcher_${{ env.sha_name }}
        path: |
           COPYING
           PSP/GAME/mhp3_patcher/EBOOT.PBP
           PSP/GAME/mhp3_patcher/PARAM.SFO
        if-no-files-found: error
